export { createClient } from "./client";
export { AuthProvider, useAuth, useUserRole } from "./components/provider/provider";
export { AuthGate } from "./components/auth-gate/auth-gate";
export { SignInModal } from "./components/sign-in-modal/sign-in-modal";
export { AccountSettings } from "./components/account-settings/account-settings";
export { ProfileSection } from "./components/account-settings/profile-section";
export { DataPrivacyModal } from "./components/account-settings/data-privacy-modal";
export { PrivacySection } from "./components/account-settings/privacy-section";
export { SupportModal } from "./components/account-settings/support-modal";
export { SupportSection } from "./components/account-settings/support-section";
export { GoogleIcon } from "./components/icons/google";
export { GithubIcon } from "./components/icons/github";
export type { AuthContextValue, AuthState, SavedAccount, UserRole } from "./types";
