var R=require("../chunks/ssr/[turbopack]_runtime.js")("server/app/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0jyhk2s._.js")
R.c("server/chunks/ssr/mono_0bqlnfk._.js")
R.c("server/chunks/ssr/1qak_next_dist_0x4z6a3._.js")
R.c("server/chunks/ssr/[root-of-the-server]__1bjer31._.js")
R.c("server/chunks/ssr/[root-of-the-server]__1012al1._.js")
R.c("server/chunks/ssr/mono_16gy0sw._.js")
R.c("server/chunks/ssr/1qak_next_dist_client_components_1xrv1u1._.js")
R.c("server/chunks/ssr/1qak_next_dist_client_components_builtin_forbidden_0e86xfm.js")
R.c("server/chunks/ssr/1qak_next_dist_client_components_builtin_unauthorized_1noxa7b.js")
R.c("server/chunks/ssr/1qak_next_dist_client_components_builtin_global-error_1tuhc2r.js")
R.c("server/chunks/ssr/mono_apps_rose__next-internal_server_app_page_actions_0kag7_p.js")
R.m(75126)
module.exports=R.m(75126).exports
